services:

  db:
    image: postgres:15
    container_name: the_goat_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:17.0
    container_name: the_goat_odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons # pour modules custom plus tard
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: the_goat_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - odoo

volumes:
  db_data:
  odoo_data:
